version: '3.8'

services:
  athena-frontend:
    image: ${FRONTEND_IMAGE}
    env_file:
      - .env
      - .frontend-secrets.env
    ports:
      - "80:80"
    restart: always
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-south-1
        awslogs-group: athena-logs
        awslogs-stream: frontend-${INSTANCE_ID}
        awslogs-create-group: "true"

  athena-backend:
    image: ${BACKEND_IMAGE}
    env_file:
      - .env
      - .backend-secrets.env
    ports:
      - "8080:80"
    restart: always
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-south-1
        awslogs-group: athena-logs
        awslogs-stream: backend
        awslogs-create-group: "true"

  athena-rnd:
    image: ${RND_IMAGE}
    env_file:
      - .env
      - .rnd-secrets.env
    ports:
      - "8081:80"
    restart: always
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-south-1
        awslogs-group: athena-logs
        awslogs-stream: rnd
        awslogs-create-group: "true"
