name: "Cross-Repo Multi-App Deployment"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - folder: "app" # Folder name in the app repo
            ecr: "atl_apac_mum_dtlk_prod_athena2.0_ecr_01"
            container: "app1"
            port: 8081
          #- folder: "app2-folder"
            #ecr: "atl_apac_mum_dtlk_prod_athena2.0_ecr_02"
            #container: "app2"
            #port: 8082
          #- folder: "app3-folder"
            #ecr: "atl_apac_mum_dtlk_prod_athena2.0_ecr_03"
            #container: "app3"
            #port: 8083

    steps:
      - name: Checkout CI/CD Repo
        uses: actions/checkout@v4

      # 1. Pull the application code from the OTHER repo
      - name: Checkout Application Repo
        uses: actions/checkout@v4
        with:
          repository: abhishek095859/test-cross
          token: ${{ secrets.APP_REPO_TOKEN }}
          path: my-apps # This pulls the whole repo into a folder called 'my-apps'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::185863138492:role/crossaccountb
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push
        id: build-step # Added an ID here
        run: |
          REGISTRY=${{ steps.login-ecr.outputs.registry }}
          FULL_IMAGE=$REGISTRY/${{ matrix.ecr }}:latest
          
          docker build -t $FULL_IMAGE ./my-apps/${{ matrix.folder }}
          docker push $FULL_IMAGE
          
          # This creates an output that the next step can definitely read
          echo "image_uri=$FULL_IMAGE" >> $GITHUB_OUTPUT

      - name: Deploy to EC2 Cluster (Both Instances)
        run: |
          aws ssm send-command \
            --targets "Key=tag:project,Values=athena2.0" \
            --document-name "AWS-RunShellScript" \
            --parameters commands="[
              \"aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}\",
              \"docker stop ${{ matrix.container }} || true\",
              \"docker rm ${{ matrix.container }} || true\",
              \"docker pull ${{ steps.build-step.outputs.image_uri }}\",
              \"docker run -d -p ${{ matrix.port }}:80 --name ${{ matrix.container }} ${{ steps.build-step.outputs.image_uri }}\",
              \"docker ps\"
            ]"
