name: " OS Hardening"

on:
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read

jobs:
  run-hardening:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::185863138492:role/crossaccountb 
          aws-region: ap-south-1

      - name: Execute Setup via SSM
        run: |
          # 1. Use jq to safely package your script into a JSON structure
          # This handles all escaping (newlines, quotes, etc.) automatically.
          jq -n --arg script "$(cat setup.sh)" '{"commands": [$script]}' > ssm_params.json

          # 2. Run the command using the file reference
          aws ssm send-command \
            --targets "Key=tag:Name1,Values=test-apollo" \
            --document-name "AWS-RunShellScript" \
            --parameters file://ssm_params.json \
            --region ap-south-1
